server:
  port: 8081

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sleeve-test?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: newpassword
  jpa:
    hibernate:
      ddl-auto: create-drop

