spring:
  profiles:
    active: dev
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    open-in-view: off
  jackson:
    property-naming-strategy: SNAKE_CASE

tailMall:
  api-package: online.loopcode.tailmall.api
